name: Build and Test

on:
  push

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-gradle-packages
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Build app
        run: ./gradlew build
      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest