name: Build and Test

on:
  push

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build app
        run: ./gradlew build
      - name: Run unit tests
        run: ./gradlew test