name: Build and Test

on:
  push

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest

    outputs:
      buildDir: ${{ steps.st }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-gradle-packages
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Build app
        run: ./gradlew build

  # TODO determine better candidates for build upload
  # TODO  whole directory takes a fair bit of time
  #        - name: Upload build artifacts
  #          uses: actions/upload-artifact@v2
  #          with:
  #            name: app-build
  #            path: app/build

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build_app

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-gradle-packages
        with:
          key: ${{ runner.os }}-test-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Run local unit tests
        run: ./gradlew test

      - name: Upload local test reports
        uses: actions/upload-artifact@v2
        with:
          name: local-unit-test-report
          path: app/build/reports/tests/testDebugUnitTest
  lint:
    name: Run Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-gradle-packages
        with:
          key: ${{ runner.os }}-lint-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-lint-
            ${{ runner.os }}-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Run linter & other checks
        run: ./gradlew lint

      - name: Upload lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

# expensive, low priority for GH actions
# TODO use reactivecircus/android-emulator-runner for running the tests
#  android_tests:
#    name: Android Tests
#    runs-on: macos-latest
#    needs: build_app
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Cache Gradle packages
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-gradle-packages
#        with:
#          key: ${{ runner.os }}-androidTest-${{ env.cache-name }}
#          restore-keys: |
#            ${{ runner.os }}-androidTest-
#            ${{ runner.os }}-
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#
#      - name: Run instrumented unit tests
#        run: ./gradlew connectedAndroidTest
#
#      - name: Upload instrumented test reports
#        uses: actions/upload-artifact@v2
#        with:
#          name: instrumented-unit-test-report
#          path: app/build/reports/androidTests/connected/testDebugUnitTest
